import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../models/subnet_filter.dart';
import '../models/subnet.dart';
import '../models/subnet_info.dart';
import '../models/subnet_metrics.dart';

part 'subnets_repository.g.dart';

@riverpod
SubnetsRepository subnetsRepository(Ref ref) {
  return const SubnetsRepository();
}

class SubnetsRepository {
  const SubnetsRepository();

  Future<List<SubnetFilter>> getFilters() async {
    return const [
      SubnetFilter(type: SubnetFilterType.all),
      SubnetFilter(type: SubnetFilterType.saved, count: '9'),
      SubnetFilter(type: SubnetFilterType.active, count: '109'),
      SubnetFilter(type: SubnetFilterType.immune, count: '12'),
      SubnetFilter(type: SubnetFilterType.atRisk, count: '109'),
      SubnetFilter(type: SubnetFilterType.validation),
    ];
  }

  Future<List<SubnetInfo>> getSubnets() async {
    return [
      SubnetInfo(
        subnet: const Subnet(
          netuid: 74,
          name: 'Apex',
          description:
              'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters.',
          alphaToken: 'A',
          category: 'Generative Ai',
          filterTags: [SubnetFilterType.saved, SubnetFilterType.active],
          watching: true,
        ),
        market: const SubnetMarket(
          price: 0.043,
          priceTrend: 1.2,
          marketCap: 202,
          volume24h: 1000000,
          emission: 46.1,
          taoLocked: 4700,
          emissionsPerHour: 46.1,
          liquidity: 194100,
          healthScore: 80,
          marketCapUsd: 86000,
          alphaUsdPrice: 15.15,
          priceHistory: [
            0.091,
            0.082,
            0.077,
            0.064,
            0.056,
            0.057,
            0.059,
            0.061,
            0.061,
            0.064,
            0.067,
            0.063,
            0.061,
            0.0595,
            0.0587,
            0.0582,
            0.0584,
            0.0581,
            0.0580,
            0.0582,
            0.0577,
            0.0568,
            0.0570,
            0.0572,
          ],
        ),
        network: const SubnetNetwork(
          networkShareRank: 103,
          tvl: 14640,
          ownerCut: 18.0,
          registrationStatus: 'Open',
          validatorCount: 12,
          validatorLimit: 64,
          minerCount: 46,
        ),
        stakers: const SubnetStakers(
          validatorSlotsFilled: 12,
          validatorSlotsTotal: 64,
          registrationLabel: 'OPEN',
          stakerApyPercent: 2893,
          estimatedValidatorEpochTau: 0.058,
          estimatedValidatorJ: 11.14,
          topValidators: [
            SubnetTopValidator(
              rank: 1,
              name: 'Foundry USA',
              takePercent: 8,
              stakeTao: 1200,
            ),
            SubnetTopValidator(
              rank: 2,
              name: 'PixelForge',
              takePercent: 12,
              stakeTao: 2500,
            ),
            SubnetTopValidator(
              rank: 3,
              name: 'CraftWorks',
              takePercent: 5,
              stakeTao: 900,
            ),
          ],
        ),
      ),
      SubnetInfo(
        subnet: const Subnet(
          netuid: 21,
          name: 'Targon',
          description:
              'Foundation model subnet centered on large-scale reasoning systems.',
          alphaToken: 'T',
          category: 'Foundation Models',
          filterTags: [SubnetFilterType.active],
        ),
        market: const SubnetMarket(
          price: 0.038,
          priceTrend: 0.8,
          marketCap: 188,
          volume24h: 847000,
          emission: 39.4,
          taoLocked: 4300,
          emissionsPerHour: 39.4,
          liquidity: 152800,
          healthScore: 77,
          marketCapUsd: 74200,
          alphaUsdPrice: 13.62,
          priceHistory: [
            0.079,
            0.074,
            0.069,
            0.061,
            0.056,
            0.052,
            0.049,
            0.046,
            0.044,
            0.041,
            0.040,
            0.039,
            0.038,
            0.039,
            0.038,
            0.038,
            0.0378,
            0.0374,
            0.0372,
            0.0376,
            0.0379,
            0.0382,
            0.0381,
            0.0380,
          ],
        ),
        network: const SubnetNetwork(
          networkShareRank: 108,
          tvl: 12120,
          ownerCut: 16.0,
          registrationStatus: 'Open',
          validatorCount: 10,
          validatorLimit: 64,
          minerCount: 42,
        ),
        stakers: const SubnetStakers(
          validatorSlotsFilled: 10,
          validatorSlotsTotal: 64,
          registrationLabel: 'OPEN',
          stakerApyPercent: 1740,
          estimatedValidatorEpochTau: 0.047,
          estimatedValidatorJ: 9.84,
          topValidators: [
            SubnetTopValidator(
              rank: 1,
              name: 'Deep Harbor',
              takePercent: 7,
              stakeTao: 1500,
            ),
            SubnetTopValidator(
              rank: 2,
              name: 'Aster Labs',
              takePercent: 10,
              stakeTao: 1100,
            ),
            SubnetTopValidator(
              rank: 3,
              name: 'Signal Mesh',
              takePercent: 6,
              stakeTao: 860,
            ),
          ],
        ),
      ),
      SubnetInfo(
        subnet: const Subnet(
          netuid: 12,
          name: 'Gradients',
          description:
              'Inference network subnet serving low-latency model execution.',
          alphaToken: 'G',
          category: 'Inference Network',
          filterTags: [SubnetFilterType.immune],
        ),
        market: const SubnetMarket(
          price: 0.051,
          priceTrend: 2.4,
          marketCap: 229,
          volume24h: 1169000,
          emission: 52.8,
          taoLocked: 5200,
          emissionsPerHour: 52.8,
          liquidity: 210400,
          healthScore: 84,
          marketCapUsd: 92100,
          alphaUsdPrice: 17.91,
          priceHistory: [
            0.064,
            0.062,
            0.060,
            0.059,
            0.057,
            0.055,
            0.053,
            0.052,
            0.051,
            0.052,
            0.053,
            0.054,
            0.055,
            0.056,
            0.057,
            0.056,
            0.055,
            0.054,
            0.053,
            0.0525,
            0.052,
            0.0515,
            0.0512,
            0.0510,
          ],
        ),
        network: const SubnetNetwork(
          networkShareRank: 97,
          tvl: 15220,
          ownerCut: 14.0,
          registrationStatus: 'Open',
          validatorCount: 14,
          validatorLimit: 64,
          minerCount: 51,
        ),
        stakers: const SubnetStakers(
          validatorSlotsFilled: 14,
          validatorSlotsTotal: 64,
          registrationLabel: 'OPEN',
          stakerApyPercent: 3121,
          estimatedValidatorEpochTau: 0.063,
          estimatedValidatorJ: 12.02,
          topValidators: [
            SubnetTopValidator(
              rank: 1,
              name: 'Vertex Node',
              takePercent: 9,
              stakeTao: 2200,
            ),
            SubnetTopValidator(
              rank: 2,
              name: 'Ion Core',
              takePercent: 11,
              stakeTao: 1900,
            ),
            SubnetTopValidator(
              rank: 3,
              name: 'Flux Capital',
              takePercent: 7,
              stakeTao: 1300,
            ),
          ],
        ),
      ),
      SubnetInfo(
        subnet: const Subnet(
          netuid: 63,
          name: 'Cortex',
          description:
              'Validation layer subnet focused on verification and trust scoring.',
          alphaToken: 'C',
          category: 'Validation Layer',
          filterTags: [SubnetFilterType.atRisk, SubnetFilterType.validation],
        ),
        market: const SubnetMarket(
          price: 0.029,
          priceTrend: 0.5,
          marketCap: 141,
          volume24h: 632000,
          emission: 31.2,
          taoLocked: 3600,
          emissionsPerHour: 31.2,
          liquidity: 120700,
          healthScore: 71,
          marketCapUsd: 60400,
          alphaUsdPrice: 10.24,
          priceHistory: [
            0.041,
            0.039,
            0.038,
            0.036,
            0.034,
            0.033,
            0.032,
            0.031,
            0.0305,
            0.030,
            0.0298,
            0.0294,
            0.0291,
            0.0289,
            0.0287,
            0.0289,
            0.0290,
            0.0292,
            0.0291,
            0.0290,
            0.0289,
            0.0288,
            0.0289,
            0.0290,
          ],
        ),
        network: const SubnetNetwork(
          networkShareRank: 119,
          tvl: 10810,
          ownerCut: 20.0,
          registrationStatus: 'Closed',
          validatorCount: 9,
          validatorLimit: 64,
          minerCount: 38,
        ),
        stakers: const SubnetStakers(
          validatorSlotsFilled: 9,
          validatorSlotsTotal: 64,
          registrationLabel: 'CLOSED',
          stakerApyPercent: 1284,
          estimatedValidatorEpochTau: 0.031,
          estimatedValidatorJ: 7.48,
          topValidators: [
            SubnetTopValidator(
              rank: 1,
              name: 'Chain Atlas',
              takePercent: 5,
              stakeTao: 980,
            ),
            SubnetTopValidator(
              rank: 2,
              name: 'Northwind',
              takePercent: 8,
              stakeTao: 760,
            ),
            SubnetTopValidator(
              rank: 3,
              name: 'Trace Ops',
              takePercent: 4,
              stakeTao: 540,
            ),
          ],
        ),
      ),
    ];
  }
}
